### PR TITLE
Fix init-aws.js to behave as expected

### PR DESCRIPTION
**Pull request by juliedavila**
There were some patterns here that were mimicking what the AWS SDK already does for you automatically, but it was only mimicking a subset of the behavior. It seems the only custom thing that is needed is to use `profile` and `region` settings in the arc config file, which I kept.

Likely fixes:
https://github.com/architect/utils/issues/22
https://github.com/architect/architect/issues/582

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [x] Expanded test coverage related to your changes:
  - [x] Added and/or updated unit tests (if appropriate)
  - [x] Added and/or updated integration tests (if appropriate)
- [x] Updated relevant documentation:
  - [x] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [x] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [x] Summarized your changes in `changelog.md`
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by juliedavila** [comment]
I am mistaken in my approach, I'll update soon

**Comment by juliedavila** [comment]
Quite of bit of adjustments here but the main thing was fixing some assumptions. Let me know what ya'll think.

**Comment by ryanblock** [comment]
I've been laid up with a gnarly bug so I'm prob going to be out of commission for a minute, but I'm looking forward to taking a look asap!

**Comment by ryanblock** [comment]
I like this! Very tidy, cleans things up nicely. :100:

Will merge and cut an RC for manual verification.

**Comment by ryanblock** [comment]
Live now in `1.4.3-RC.0`!

**Pull request merged**
