### PR TITLE
Add log levels, return all logged data

### PR DESCRIPTION
**Pull request by ryanblock**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [x] Expanded test coverage related to your changes:
  - [x] Added and/or updated unit tests (if appropriate)
  - [x] Added and/or updated integration tests (if appropriate)
- [x] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [x] Summarized your changes in `changelog.md`
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by filmaj** [comment]
cool!

They key for me is how `architect/architect` integrates this. I'd love for us to be able to litter the code with tons of logging, but then have the user be able to 'opt in' to printing that out depending on what cli flags they feed into the command. As we discussed on a recent call I think this could be achieved with an event emitter within arc, but then if this module is directly invoking `console.log`, that won't work.

**Comment by ryanblock** [comment]
As an alternative to rewriting to an event emitter API, I'm playing around with expanding the normal updater API to look like this:
```
// normal
update = updater('whatev')
update.status('this will print')
update.verbose.status('this will not print')
update.debug.status('this will not print')
// verbose mode
update = updater('whatev', { logLevel: 'verbose' })
update.status('this will print')
update.verbose.status('this will print')
update.debug.status('this will not print')
// debug mode
update = updater('whatev', { logLevel: 'debug' })
update.status('this will print')
update.verbose.status('this will print')
update.debug.status('this will print')
```

CLI callers pass a `logLevel` param (currently one of 'quiet', 'normal', 'verbose', 'debug' ); any log level higher than specified will be ignored (defaulting to `normal`).

**Comment by filmaj** [comment]
Oh that's rad. Hell yeah! This will make user bug reports and even delving into test failures so much easier!

**Comment by ryanblock** [comment]
Yeah, I'm thinking users would want `verbose` mode, and internally we'd probably want `debug` mode. This change should be a drop-in. I'd also like it to output all the log data for processing doing it's not as functional as I'd like, but it seems to be going ok so far.

**Comment by filmaj** [comment]
So in terms of integration with the other arc packages, tell me if this sounds right to you:

- `@architect/architect` will parse environment variables and/or CLI flags passed into it to set log level, instantiate an `updater` instance, then pass that `updater` instance along to all the other packages depending on the command being invoked
- all other packages will either use a passed-in `updater` instance, or create one themselves (and possibly need to do the same env var/CLI flag checking to set log level in this situation too?)

**Review by filmaj — APPROVED** [review]

**Comment by ryanblock** [comment]
Yeah that's right, although arc/arc won't need to pass the updater to individual child modules, as each of those is usually responsible for setting their own cli flags anyway. And either way, in theory, Node should have updater's buffer in global scope at all times.

**Comment by filmaj** [comment]
>  And either way, in theory, Node should have updater's buffer in global scope at all times.

As the code stands right now, not sure that would be the case, as `params` would be constructed on each initialization, and since `data` (assuming this is the log "buffer" you mentioned?) is a string, that would be passed-by-value, so I _think_ each invocation of `updater('blah')` would create a new buffer.

I think we could handle this issue by moving the `params` object into global scope of the updater module.

**Comment by ryanblock** [comment]
The `data` in global scope was consistently being updated across modules/instantiations (in my limited testing). However, I did find a funky bug where changing other updater options after initial instantiation could create new copies of everything. This only came up in tests and I wouldn't expect to see that in the real world, but who knows – resolved in https://github.com/architect/utils/pull/178/commits/81b7855f3876926a36ea8939814ffe150bff91c8 by moving `data` into the updater methods submodule.

Keeping params in local scope does allow some super fine-granined configurability that I doubt we'll ever need but either way I'd like to try to keep it there to reduce the amount of global state we're maintaining. I already kind of hate this global scope hack but eh.

**Pull request merged**
